name: four_functions_problems
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  intl: ^0.18.0  # Use the latest version

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
